//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTimeZones
    {
        public short TimeZoneID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> SunStart { get; set; }
        public Nullable<System.DateTime> SunEnd { get; set; }
        public Nullable<System.DateTime> MonStart { get; set; }
        public Nullable<System.DateTime> MonEnd { get; set; }
        public Nullable<System.DateTime> TuesStart { get; set; }
        public Nullable<System.DateTime> TuesEnd { get; set; }
        public Nullable<System.DateTime> WedStart { get; set; }
        public Nullable<System.DateTime> WedEnd { get; set; }
        public Nullable<System.DateTime> ThursStart { get; set; }
        public Nullable<System.DateTime> ThursEnd { get; set; }
        public Nullable<System.DateTime> FriStart { get; set; }
        public Nullable<System.DateTime> FriEnd { get; set; }
        public Nullable<System.DateTime> SatStart { get; set; }
        public Nullable<System.DateTime> SatEnd { get; set; }
    }
}
