//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACUnlockComb
    {
        public short UnlockCombID { get; set; }
        public string Name { get; set; }
        public Nullable<short> Group01 { get; set; }
        public Nullable<short> Group02 { get; set; }
        public Nullable<short> Group03 { get; set; }
        public Nullable<short> Group04 { get; set; }
        public Nullable<short> Group05 { get; set; }
    }
}
