//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmLog
    {
        public int ID { get; set; }
        public string Operator { get; set; }
        public string EnrollNumber { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string MachineAlias { get; set; }
        public Nullable<int> AlarmType { get; set; }
    }
}
