//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditedExc
    {
        public int AEID { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime CheckTime { get; set; }
        public Nullable<int> NewExcID { get; set; }
        public Nullable<short> IsLeave { get; set; }
        public string UName { get; set; }
        public System.DateTime UTime { get; set; }
    }
}
