//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKEXACT
    {
        public int EXACTID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> CHECKTIME { get; set; }
        public string CHECKTYPE { get; set; }
        public Nullable<short> ISADD { get; set; }
        public string YUYIN { get; set; }
        public Nullable<short> ISMODIFY { get; set; }
        public Nullable<short> ISDELETE { get; set; }
        public Nullable<short> INCOUNT { get; set; }
        public Nullable<short> ISCOUNT { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
