//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENTS
    {
        public int DEPTID { get; set; }
        public string DEPTNAME { get; set; }
        public int SUPDEPTID { get; set; }
        public Nullable<short> InheritParentSch { get; set; }
        public Nullable<short> InheritDeptSch { get; set; }
        public Nullable<short> InheritDeptSchClass { get; set; }
        public Nullable<short> AutoSchPlan { get; set; }
        public Nullable<short> InLate { get; set; }
        public Nullable<short> OutEarly { get; set; }
        public Nullable<short> InheritDeptRule { get; set; }
        public Nullable<int> MinAutoSchInterval { get; set; }
        public Nullable<short> RegisterOT { get; set; }
        public int DefaultSchId { get; set; }
        public Nullable<short> ATT { get; set; }
        public Nullable<short> Holiday { get; set; }
        public Nullable<short> OverTime { get; set; }
    }
}
