//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaceTemp
    {
        public int TEMPLATEID { get; set; }
        public string USERNO { get; set; }
        public Nullable<int> SIZE { get; set; }
        public Nullable<int> pin { get; set; }
        public Nullable<int> FACEID { get; set; }
        public Nullable<int> VALID { get; set; }
        public Nullable<int> RESERVE { get; set; }
        public Nullable<int> ACTIVETIME { get; set; }
        public Nullable<int> VFCOUNT { get; set; }
        public byte[] TEMPLATE { get; set; }
    }
}
