//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLIDAYS
    {
        public int HOLIDAYID { get; set; }
        public string HOLIDAYNAME { get; set; }
        public Nullable<short> HOLIDAYYEAR { get; set; }
        public Nullable<short> HOLIDAYMONTH { get; set; }
        public Nullable<short> HOLIDAYDAY { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<short> DURATION { get; set; }
        public Nullable<short> HOLIDAYTYPE { get; set; }
        public string XINBIE { get; set; }
        public string MINZU { get; set; }
        public Nullable<short> DeptID { get; set; }
    }
}
