//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machines
    {
        public int ID { get; set; }
        public string MachineAlias { get; set; }
        public int ConnectType { get; set; }
        public string IP { get; set; }
        public Nullable<int> SerialPort { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<int> Baudrate { get; set; }
        public int MachineNumber { get; set; }
        public Nullable<bool> IsHost { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string CommPassword { get; set; }
        public Nullable<short> UILanguage { get; set; }
        public Nullable<short> DateFormat { get; set; }
        public Nullable<short> InOutRecordWarn { get; set; }
        public Nullable<short> Idle { get; set; }
        public Nullable<short> Voice { get; set; }
        public Nullable<short> managercount { get; set; }
        public Nullable<short> usercount { get; set; }
        public Nullable<short> fingercount { get; set; }
        public Nullable<short> SecretCount { get; set; }
        public string FirmwareVersion { get; set; }
        public string ProductType { get; set; }
        public Nullable<short> LockControl { get; set; }
        public Nullable<short> Purpose { get; set; }
        public Nullable<int> ProduceKind { get; set; }
        public string sn { get; set; }
        public string PhotoStamp { get; set; }
        public Nullable<int> IsIfChangeConfigServer2 { get; set; }
    }
}
