//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUM_RUN
    {
        public int NUM_RUNID { get; set; }
        public Nullable<int> OLDID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<short> CYLE { get; set; }
        public Nullable<short> UNITS { get; set; }
    }
}
