//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportItem
    {
        public int RIID { get; set; }
        public Nullable<int> RIIndex { get; set; }
        public Nullable<short> ShowIt { get; set; }
        public string RIName { get; set; }
        public string UnitName { get; set; }
        public byte[] Formula { get; set; }
        public Nullable<short> CalcBySchClass { get; set; }
        public Nullable<short> StatisticMethod { get; set; }
        public Nullable<short> CalcLast { get; set; }
        public byte[] Notes { get; set; }
    }
}
