//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchClass
    {
        public int schClassid { get; set; }
        public string schName { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<int> LateMinutes { get; set; }
        public Nullable<int> EarlyMinutes { get; set; }
        public Nullable<int> CheckIn { get; set; }
        public Nullable<int> CheckOut { get; set; }
        public Nullable<System.DateTime> CheckInTime1 { get; set; }
        public Nullable<System.DateTime> CheckInTime2 { get; set; }
        public Nullable<System.DateTime> CheckOutTime1 { get; set; }
        public Nullable<System.DateTime> CheckOutTime2 { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<short> AutoBind { get; set; }
        public Nullable<double> WorkDay { get; set; }
        public string SensorID { get; set; }
        public Nullable<double> WorkMins { get; set; }
    }
}
