//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITYDETAILS
    {
        public int SECURITYDETAILID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<short> DEPTID { get; set; }
        public Nullable<short> SCHEDULE { get; set; }
        public Nullable<short> USERINFO { get; set; }
        public Nullable<short> ENROLLFINGERS { get; set; }
        public Nullable<short> REPORTVIEW { get; set; }
        public string REPORT { get; set; }
        public Nullable<bool> ReadOnly { get; set; }
        public Nullable<bool> FullControl { get; set; }
    }
}
