//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerLog
    {
        public int ID { get; set; }
        public string EVENT { get; set; }
        public int USERID { get; set; }
        public string EnrollNumber { get; set; }
        public Nullable<short> parameter { get; set; }
        public System.DateTime EVENTTIME { get; set; }
        public string SENSORID { get; set; }
        public string OPERATOR { get; set; }
    }
}
