//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIFT
    {
        public int SHIFTID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> USHIFTID { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<short> RUNNUM { get; set; }
        public Nullable<int> SCH1 { get; set; }
        public Nullable<int> SCH2 { get; set; }
        public Nullable<int> SCH3 { get; set; }
        public Nullable<int> SCH4 { get; set; }
        public Nullable<int> SCH5 { get; set; }
        public Nullable<int> SCH6 { get; set; }
        public Nullable<int> SCH7 { get; set; }
        public Nullable<int> SCH8 { get; set; }
        public Nullable<int> SCH9 { get; set; }
        public Nullable<int> SCH10 { get; set; }
        public Nullable<int> SCH11 { get; set; }
        public Nullable<int> SCH12 { get; set; }
        public Nullable<short> CYCLE { get; set; }
        public Nullable<short> UNITS { get; set; }
    }
}
