//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSMSINFO
    {
        public int REFERENCE { get; set; }
        public string SMSID { get; set; }
        public int SMSINDEX { get; set; }
        public Nullable<int> SMSTYPE { get; set; }
        public string SMSCONTENT { get; set; }
        public string SMSSTARTTM { get; set; }
        public Nullable<int> SMSTMLENG { get; set; }
        public string GENTM { get; set; }
    }
}
