//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserACPrivilege
    {
        public int UserID { get; set; }
        public int DeviceID { get; set; }
        public Nullable<int> ACGroupID { get; set; }
        public Nullable<bool> IsUseGroup { get; set; }
        public Nullable<int> TimeZone1 { get; set; }
        public Nullable<int> TimeZone2 { get; set; }
        public Nullable<int> TimeZone3 { get; set; }
        public Nullable<int> verifystyle { get; set; }
    }
}
