//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_OF_RUN
    {
        public int USERID { get; set; }
        public int NUM_OF_RUN_ID { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public Nullable<int> ISNOTOF_RUN { get; set; }
        public Nullable<int> ORDER_RUN { get; set; }
    }
}
