//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldemGym.Acceso.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SPEDAY
    {
        public int USERID { get; set; }
        public System.DateTime STARTSPECDAY { get; set; }
        public Nullable<System.DateTime> ENDSPECDAY { get; set; }
        public short DATEID { get; set; }
        public string YUANYING { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
